connector_image: airbyte/source-excel-sheets:dev
test_strictness_level: high
acceptance_tests:
  spec:
    tests:
      - spec_path: "manifest.yaml"
  connection:
    tests:
      - config_path: "secrets/config.json"
        status: "succeed"
      - config_path: "integration_tests/invalid_config.json"
        status: "exception"
  discovery:
    tests:
      - config_path: "secrets/config.json"
        backward_compatibility_tests_config:
          disable_for_version: "0.1.0"
  basic_read:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
        expect_records:
          path: "integration_tests/expected_records.txt"
          exact_order: false
        empty_streams:
          - name: empty_worksheet
            bypass_reason: "This worksheet is expected to be empty for testing purposes"
  full_refresh:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"